// Code generated by cmd/build_metadata; DO NOT EDIT.

package emailverifier

// map to store domains never to be treated as disposable
var allowedDisposableDomains = map[string]bool {
	"4x4man.com": true,
	"alphafrau.de": true,
	"mail2world.com": true,
	"qmail.com": true,
	"hush.com": true,
	"lavabit.com": true,
}