package emailverifier

// suggestionDomains are domains to check misspelled domains
var suggestionDomains = map[string]bool{
	"msn.com":         true,
	"bellsouth.net":   true,
	"telus.net":       true,
	"comcast.net":     true,
	"optusnet.com.au": true,
	"earthlink.net":   true,
	"qq.com":          true,
	"sky.com":         true,
	"icloud.com":      true,
	"mac.com":         true,
	"sympatico.ca":    true,
	"googlemail.com":  true,
	"att.net":         true,
	"xtra.co.nz":      true,
	"web.de":          true,
	"cox.net":         true,
	"gmail.com":       true,
	"ymail.com":       true,
	"aim.com":         true,
	"rogers.com":      true,
	"verizon.net":     true,
	"rocketmail.com":  true,
	"google.com":      true,
	"optonline.net":   true,
	"sbcglobal.net":   true,
	"aol.com":         true,
	"me.com":          true,
	"btinternet.com":  true,
	"charter.net":     true,
	"shaw.ca":         true,
}

// suggestionSecondLevelDomains are second level domains to check misspelled domains
var suggestionSecondLevelDomains = map[string]bool{
	"yahoo":   true,
	"hotmail": true,
	"mail":    true,
	"live":    true,
	"outlook": true,
	"gmx":     true,
}

// suggestionTopLevelDomains are top level domains to check misspelled domains
var suggestionTopLevelDomains = map[string]bool{
	"com":    true,
	"com.au": true,
	"com.tw": true,
	"ca":     true,
	"co.nz":  true,
	"co.uk":  true,
	"de":     true,
	"fr":     true,
	"it":     true,
	"ru":     true,
	"org":    true,
	"edu":    true,
	"gov":    true,
	"jp":     true,
	"nl":     true,
	"kr":     true,
	"se":     true,
	"eu":     true,
	"ie":     true,
	"co.il":  true,
	"us":     true,
	"at":     true,
	"be":     true,
	"dk":     true,
	"hk":     true,
	"es":     true,
	"gr":     true,
	"ch":     true,
	"no":     true,
	"cz":     true,
	"in":     true,
	"net":    true,
	"net.au": true,
	"info":   true,
	"biz":    true,
	"mil":    true,
	"co.jp":  true,
	"sg":     true,
	"hu":     true,
	"uk":     true,
}
